language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: GQAo96xtGF9ilYw3FFuUZFjLLht7zOxGq0NlQwdpjWyEiRogQLT9iqoSKEQCZR3R705uHGR3QyZyYZS591FhZUJxmnj1zrQ60ehsoTh71Xk/5kxtwJN/rndlVUQn2oBm4xRz32HqUlIoGZrqqCTjpN3sfgtfQ2JtsYs1MgHdkaupPDKsT/Gx9I6s8T5ZkhdZTDSfx/Pejc00A+9Ky3lr1ZF9kPfWJullfgcnwdPxZS38yauzZ9s4QFwl6fLQaQLwKeDYDzzqUcIctXxu5cuussgaDYxdWhvo9vKTfqF9Z9wSRE6T4mUDo5Hpo2L5ShBYnmIb3PSJ7zovuquM+mDu/6KFUed2A4Fz0XMh+Bw9Kk3lYJnIQhtaUgkLdOidZD8wOtGRG0bZaZc/iLalxvVYh7oHLmnS2fV9yUXsDQhMllg0Fal2jxi2sWD7AkUoGTPkpXFHyfc4Xv2lqGmnWhzokG0LVwGtagBADzZqqpndbfpMItz1s/rpCzrCYjDHCxXMyZJM+XL4yFapXSP00ZEmZaBB0OcKBPpf1kDyf6xXHVQCO4GXWmB/HaqTUZiu9C0eVfcHMfmt43Cgxk/F36IaMTgzvD/UVQAg0op2uXVisk9Vq9o7cfg0O0ZvLfdkgh+MWUMS6MEZ6rrRnbdtAvgkkmRifEinl5eF9sj/5p6TEAo=
